### ISSUE TITLE
Mantid doesn't build with GSL 2

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#15421]
Mantid fails to build with GSL 2 which will be on Ubuntu 16.04 and Fedora 24. We will need to support Ubuntu 16.04 for the `3.7` release.

We have a Ubuntu 16.04 [build server](http://builds.mantidproject.org/job/master_clean-ubuntu-16.04/). Feel free to point it at your working branch to use for testing.

The type of errors that are appearing:
```
02:04:46 /home/builder/jenkins-linode/workspace/master_clean-ubuntu-16.04/Framework/CurveFitting/src/Algorithms/Fit1D.cpp: In member function ‘virtual void Mantid::CurveFitting::Algorithms::Fit1D::exec()’:
02:04:46 /home/builder/jenkins-linode/workspace/master_clean-ubuntu-16.04/Framework/CurveFitting/src/Algorithms/Fit1D.cpp:615:29: error: ‘struct gsl_multifit_fdfsolver’ has no member named ‘J’
02:04:46        gsl_multifit_covar(s->J, 0.0, covar);
```

**Comment by rosswhitfield** [comment]
Here is an example of a patch required to go from gsl 1 to 2 for qtiplot, from [here](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/qtiplot-gsl2.patch?h=packages/qtiplot&id=c5e8e49355cc1a3bed20604f208a9091ac4cb98b).
```diff
Description: adoptation to gsl2.
Author: Damir Islamov <damir@secretlaboratory.ru>
Last-Update: 2015-12-04

--- a/qtiplot/src/analysis/Fit.cpp
+++ b/qtiplot/src/analysis/Fit.cpp
@@ -126,10 +126,12 @@ gsl_multifit_fdfsolver * Fit::fitGSL(gsl
 			break;
 		}
 	}
-
+	gsl_matrix *J = gsl_matrix_alloc(d_n, d_p);
 	if (status){
-	    gsl_multifit_covar (s->J, 0.0, covar);
+	    gsl_multifit_fdfsolver_jac(s, J);
+	    gsl_multifit_covar (J, 0.0, covar);
 	    iterations = 0;
+	    gsl_matrix_free (J);
 	    return s;
 	}
 
@@ -154,9 +156,9 @@ gsl_multifit_fdfsolver * Fit::fitGSL(gsl
 
 		status = gsl_multifit_test_delta (s->dx, s->x, d_tolerance, d_tolerance);
 	} while (inRange && status == GSL_CONTINUE && (int)iter < d_max_iterations);
-
-	gsl_multifit_covar (s->J, 0.0, covar);
-
+	gsl_multifit_fdfsolver_jac(s, J);
+	gsl_multifit_covar (J, 0.0, covar);
+	gsl_matrix_free (J);
 	iterations = iter;
 	return s;
 }
```

**Comment by AndreiSavici** [comment]
```
The following tests FAILED:
	447 - PythonAlgorithms_ComputeCalibrationCoefVanTest (Failed)
	462 - PythonAlgorithms_EnggFitPeaksTest (Failed)
	478 - PythonAlgorithms_IqtFitMultipleTest (Failed)
	488 - PythonAlgorithms_LoadNMoldyn4AsciiTest (Failed)
	494 - PythonAlgorithms_MolDynTest (Failed)
	520 - PythonAlgorithms_TOFTOFConvertTofToDeltaETest (Failed)
	1105 - CurveFittingTest_MultiDomainFunctionTest (Failed)
	1142 - CrystalTest_OptimizeCrystalPlacementTest (Failed)
```

**Comment by AndreiSavici** [comment]
The following doc tests have problems:
```
EnggCalibrate-v1.rst
FitPeak-v1.rst
EnggFitPeaks-v1.rst
ConvolutionFitSequential-v1.rst
SaveMDWorkspaceToVTK-v1.rst
```
The last one is failing because I did not build with `MAKE_VATES` option. It is still annoying that the test is run, even when the algorithm is not registered

**Comment by AndreiSavici** [comment]
I did not check yet if all the problems in systemtests are related to gsl, but the failed ones are:
```
FAILED:
SANSFileChecking.SANSSwitchIDFTestRunner
SANS2DSlicing.SANS2DMinimalBatchReductionSliced
SANS2DSlicing.SANS2DMinimalSingleReductionSliced
WeightedLeastSquaresTest.WeightedLeastSquaresTest
CalibrateRectangularDetector_Test.PG3CCCalibration
SANSLoadersTest.LoadAddedEventDataSampleTestStressTest
SANS2DMultiPeriod.SANS2DMultiPeriodBatch
SANS2DMultiPeriod.SANS2DMultiPeriodSingle
SANS2DReductionGUI.SANS2DGUIBatchReduction
EnggCalibrationTest.EnginXCalibrateFullThenCalibrateTest
SANS2DLimitEventsTime.SANS2DLimitEventsTime
ISISIndirectInelastic.OSIRISConvFit
ISISIndirectInelastic.OSIRISFuryAndFuryFit
ISISIndirectInelastic.OSIRISIqtAndIqtFitMulti
VesuvioCorrectionsTest.GammaAndMsCorrectWorkspaceIndexOne
VesuvioCorrectionsTest.TestGammaAndMsCorrectWorkspaceIndexTwo
SANS2DBatch.SANS2DBatch
SANS2DBatch.SANS2DNewSettingsCarriedAcrossInBatchMode
SANS2DMultiPeriodAddFiles.SANS2DMultiPeriodAddFiles
SANSQResolutionTest.SANSQResolutionWithGravity
SANSQResolutionTest.SANSQResolutionWithoutGravity
SANS2DReductionGUIAdded.SANS2DReductionGUIAddedFiles
SANS2DReductionGUI.SANS2DGUIReduction
SANS2DReductionGUI.SANS2DMinimalBatchReduction
SANS2DReductionGUI.SANS2DMinimalSingleReduction
SANS2DFrontNoGrav.SANS2DFrontNoGrav
SANS2DFrontNoGrav.SANS2DWithExtraLengthGravity
ISISIndirectInelastic.IRISConvFit
ISISIndirectInelastic.IRISFuryAndFuryFit
ISISIndirectInelastic.IRISIqtAndIqtFitMulti

90% tests passed, 30 tests failed out of 313 (22 skipped)
All tests passed? False
```

**Comment by rosswhitfield** [comment]
Looks like you're missing `python-nxs` on your system, see #15655

**Comment by AndreiSavici** [comment]
Slightly better:

```
FAILED:
CalibrateRectangularDetector_Test.PG3CCCalibration
WeightedLeastSquaresTest.WeightedLeastSquaresTest
ISISIndirectInelastic.OSIRISConvFit
ISISIndirectInelastic.OSIRISFuryAndFuryFit
ISISIndirectInelastic.OSIRISIqtAndIqtFitMulti
ISISIndirectInelastic.IRISConvFit
ISISIndirectInelastic.IRISFuryAndFuryFit
ISISIndirectInelastic.IRISIqtAndIqtFitMulti
EnggCalibrationTest.EnginXCalibrateFullThenCalibrateTest
VesuvioCorrectionsTest.GammaAndMsCorrectWorkspaceIndexOne
VesuvioCorrectionsTest.TestGammaAndMsCorrectWorkspaceIndexTwo

96% tests passed, 11 tests failed out of 313 (22 skipped)
All tests passed? False
```

**Comment by mantid-roman** [comment]
@rosswhitfield @AndreiSavici Could you check if it's better now?

**Comment by rosswhitfield** [comment]
👍 `EnggFitPeaksTest` and `IntegratePeakTimeSlicesTest` now pass. 😃 

With `SCDCalibratePanelsTest` did you just comment out the test?

I still have `EnggFitDIFCFromPeaksTest` and `OptimizeCrystalPlacementTest` failing.

**Comment by mantid-roman** [comment]
I think I did :disappointed:

**Comment by mantid-roman** [comment]
Do you have the error message for `OptimizeCrystalPlacementTest `? It passes for me.

**Comment by rosswhitfield** [comment]
That test sporadically fails for me. From [here](http://builds.mantidproject.org/job/master_clean-ubuntu-16.04/47/testReport/junit/CrystalTest/OptimizeCrystalPlacementTest/test_basic/)

```
Stacktrace

Error: Expected (d == 0) up to .3 (0.3000), found (1.0817 != 0)
Error: Expected (d == 0) up to .3 (0.3000), found (1.2182 != 0)
Standard Output

Fit finished. Status=success
Fit finished. Status=success

In OptimizeCrystalPlacementTest::test_basic:
/home/builder/jenkins-linode/workspace/master_clean-ubuntu-16.04/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to .3 (0.3000), found (1.0817 != 0)
/home/builder/jenkins-linode/workspace/master_clean-ubuntu-16.04/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to .3 (0.3000), found (1.2182 != 0)
```

**Comment by NickDraper** [comment]
This woulod be too risky to include in R3.7 now, moving to R3.8

**Comment by mantid-roman** [comment]
Somebody with better knowledge of `OptimizeCrystalPlacement` needs to have a look at `test_basic` and probably redesign it. The fits there are ill-conditioned and I have no idea how to make them stable.

**Comment by rosswhitfield** [comment]
If you want to open a pull request for what you have done so far it would be good to get it into master, we can then find someone else to look at `OptimizeCrystalPlacement`.

**Comment by mantid-roman** [comment]
This test will have to be disabled

**Comment by rosswhitfield** [comment]
No? We aren't using gsl 2 on any of our officially supported platforms yet, so the pull request will pass. We just need to solve this problem before we can support Ubuntu 16.04.
