### PR TITLE
Fix failing doctests

### LINKED ISSUE #35073: Fix failing doc-tests
After the following doc-tests are fixed, running them should be re-enabled on the osx build. 

To coordinate work, please add your name/facility to items when work is started.

From doing a full run locally the following doctests are failing for me (someone should verify):

# Todo
- [x] algorithms/ConvolveWorkspaces-v1.rst
- [x] algorithms/CorrectTOFAxis-v1.rst - 2 failures test
- [x] algorithms/CreateEPP-v1.rst
- [x] algorithms/CreateSampleWorkspace-v1.rst
- [x] algorithms/FindEPP-v2.rst
- [x] algorithms/FindPeaks-v1.rst
- [x] algorithms/Fit-v1.rst
- [x] algorithms/FitGaussian-v1.rst
- [x] algorithms/FitPeaks-v1.rst
- [x] algorithms/GetDetectorOffsets-v1.rst
- [x] algorithms/HB3AIntegrateDetectorPeaks-v1.rst
- [x] algorithms/IntegrateEPP-v1.rst
- [x] algorithms/Integration-v1.rst
- [x] algorithms/LoadEMU-v1.rst
- [x] algorithms/LoadILLTOF-v2.rst
- [x] algorithms/LoadSESANS-v1.rst- Test and cleanup code
- [x] algorithms/MatchPeaks-v1.rst
- [x] algorithms/MayersSampleCorrection-v1.rst
- [x] algorithms/MSDFit-v1.rst
- [x] ~~algorithms/SaveVulcanGSS-v1.rst~~ Algorithm hard deprecated, usage code removed. 
- [x] techniques/PolarisedDiffractionILL.rstsave
- [x] algorithms/EnggSaveGSASIIFitResultsToHDF5-v1.rst
- [x] techniques/ReflectometryILL.rst
- [x] algorithms/PolDiffILLReduction-v1

# Not erroring (for @ConorMFinn on Ubuntu 18.04)
- [x] algorithms/ConvertSnsRoiFileToMask-v1.rst - test and cleanup code
- [x] algorithms/CorelliCalibrationDatabase-v1.rst
- [x] algorithms/EnggCalibrateFull-v1.rst - test and cleanup code
- [x] algorithms/LoadDetectorsGroupingFile-v1.rst- 2 failures test - 2 cleanup code failures
- [x] algorithms/LoadNXcanSAS-v1.rst
- [x] algorithms/SaveDaveGrp-v1.rst
- [x] algorithms/SaveFITS-v1.rst- just cleanup code
- [x] algorithms/SaveMD-v1.rst
- [x] algorithms/SaveMD-v2.rst - test and cleanup code
- [x] algorithms/SaveNXcanSAS-v1.rst
- [x] algorithms/SpatialGrouping-v1.rst- Test and cleanup code
- [x] algorithms/SpecularReflectionPositionCorrect-v2.rst

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**

Updated doctests to take into account other code changes. 

**To test:**
1. Build workbench and `AllTests` target. Then open workbench and in ManangeUserDirectories add the paths to the UnitTests and DocTests in the test data. Close workbench.
2. Build the `docs-doctest` target and check all tests pass

Fixes #35073 

**Note: One of the jenkins pipelines will need updating to add the `--enable-doctests` to the buildscript call. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jhaigh0** [comment]
Had some failures unfortunately
```
Expected:
41>    Position of Detector ID=1100 in 1st workspace: 9,0,0
41>    Position of Detector ID=1101 in 1st workspace: 10,3,0
41>    Position of Detector ID=1103 in 1st workspace: 12,3,6
41>    Position of Detector ID=1100 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1101 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1103 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1100 in 2nd workspace after CopyInstrumentParameters: 9,0,0
41>    Position of Detector ID=1101 in 2nd workspace after CopyInstrumentParameters: 10,3,0
41>    Position of Detector ID=1103 in 2nd workspace after CopyInstrumentParameters: 12,3,6
41>Got:
41>    Position of Detector ID=1100 in 1st workspace: 9,0,0
41>    Position of Detector ID=1101 in 1st workspace: 10,3,0
41>    Position of Detector ID=1103 in 1st workspace: 12,3,6
41>    Position of Detector ID=1100 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1101 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1103 in 2nd workspace before CopyInstrumentParameters: 0,0,-1
41>    Position of Detector ID=1100 in 2nd workspace after CopyInstrumentParameters: 9,-0,0
41>    Position of Detector ID=1101 in 2nd workspace after CopyInstrumentParameters: 10,3,0
41>    Position of Detector ID=1103 in 2nd workspace after CopyInstrumentParameters: 12,3,6
41>**********************************************************************
41>1 items had failures:
41>   1 of   1 in ExCopyInstrumentParametersSimple
41>1 tests in 1 items.
41>0 passed and 1 failed.
41>***Test Failed*** 1 failures.
```
This is a 0 vs -0 problem.

```
41>Expected:
41>    Number of components = 5
41>    bank1 file sim_corelli_cal/bank1.csv exist = True
41>    calibration file sim_corelli_cal/corelli_instrument_20200220.csv exist = True
41>Got:
41>    Number of components = 5
41>    bank1 file sim_corelli_cal\bank1.csv exist = True
41>    calibration file sim_corelli_cal\corelli_instrument_20200220.csv exist = True
41>**********************************************************************
41>1 items had failures:
41>   1 of   1 in CorelliPowderCalibrationExample
41>1 tests in 1 items.
41>0 passed and 1 failed.
41>***Test Failed*** 1 failures.
```
This is a file separator problem.

```
41>File "algorithms\SaveReflectometryAscii-v1.rst", line 128, in SaveReflectometryAscii_general_usage (cleanup code)
41>Failed example:
41>    if os.path.exists(file + ".mft"):
41>      # Delete file
41>      os.remove(file + ".mft")
41>Exception raised:
41>    Traceback (most recent call last):
41>      File "C:\Users\bya67386\AppData\Local\mambaforge\envs\mantid-developer\lib\doctest.py", line 1336, in __run
41>        exec(compile(example.source, filename, "single",
41>      File "<doctest SaveReflectometryAscii_general_usage (cleanup code)[0]>", line 3, in <module>
41>        os.remove(file + ".mft")
41>    PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bya67386\\ws.mft'
41>1 items passed all tests:
41>   1 tests in SaveReflectometryAscii_general_usage
41>1 tests in 1 items.
41>1 passed and 0 failed.
41>Test passed.
41>**********************************************************************
41>1 items had failures:
41>   1 of   2 in SaveReflectometryAscii_general_usage (cleanup code)
41>2 tests in 1 items.
41>1 passed and 1 failed.
41>***Test Failed*** 1 failures.
```
Some discussion on this error message [here](https://github.com/Belval/pdf2image/issues/151#issuecomment-709376796) and [here](https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is)

**Comment by ConorMFinn** [comment]
We don't intend to ever run these tests on windows (Mac is currently looking to be the most likely candidate, currently). Maybe it's worth checking on another OS before committing to fixes? @martyngigg @DanielMurphy22 Could this have a quick mac test if you have time?

**Review by jhaigh0 — DISMISSED** [review]
All the previously failing tests (for windows) now pass, running them individually.

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
2 failures tested on MacOS:

```
**********************************************************************
File "techniques/ReflectometryILL.rst", line 799, in D17UserAngleQuartz
Failed example:
    # reduction based on data from cycle 213, internalUse, quartz sample
    name = 'D17_Quartz_213'
    direct_beams = ','.join(['676978'] * 4)
    reflected_beams = '676979,676980,676981+676982,676983+676985'
    wavelength_lower = [3.7, 3, 3, 3]
    wavelength_upper = 24
    user_angles = [0.406, 0.806, 1.609, 3.207]
    ReflectometryILLAutoProcess(
       Run=reflected_beams,
       DirectRun=direct_beams,
       OutputWorkspace=name,
       SummationType='Incoherent',
       WavelengthLowerBound=wavelength_lower,
       WavelengthUpperBound=wavelength_upper,
       DeltaQFractionBinning=0.5,
       AngleOption='UserAngle',
       Theta=user_angles,
       DirectLowAngleFrgHalfWidth=[3, 3, 3, 3],
       DirectHighAngleFrgHalfWidth=[3, 5, 7, 9],
       ReflLowAngleFrgHalfWidth=[3, 5, 7, 9],
       ReflHighAngleFrgHalfWidth=[3, 5, 7, 9],
       DirectLowAngleBkgOffset=5,
       DirectLowAngleBkgWidth=10,
       DirectHighAngleBkgOffset=5,
       DirectHighAngleBkgWidth=10,
       ReflLowAngleBkgOffset=5,
       ReflLowAngleBkgWidth=10,
       ReflHighAngleBkgOffset=5,
       ReflHighAngleBkgWidth=10,
    )
    print("Number of output workspaces: {}".format(mtd[name].getNumberOfEntries()))
    print("Momentum exchange ranges: {:.4f}, {:.4f}".format(mtd[name][2].readX(0)[0], mtd[name][2].readX(0)[-1]))
    print('X unit: ' + mtd[name][0].getAxis(0).getUnit().unitID())
Exception raised:
    Traceback (most recent call last):
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 936, in do_set_property
        alg_object.setProperty(key, new_value)
    ValueError: Invalid value for property Run (list of str lists) from string "676979,676980,676981+676982,676983+676985": Unable to find file matching the string "676979", please check the data search directories.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/Users/danielmurphy/mambaforge/envs/mantid-developer/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest D17UserAngleQuartz[0]>", line 8, in <module>
        ReflectometryILLAutoProcess(
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1068, in __call__
        set_properties(algm, *args, **final_keywords)
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 956, in set_properties
        do_set_property(key, value)
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 939, in do_set_property
        raise e.__class__(msg) from e
    ValueError: Problem setting "Run" in ReflectometryILLAutoProcess-v1: Invalid value for property Run (list of str lists) from string "676979,676980,676981+676982,676983+676985": Unable to find file matching the string "676979", please check the data search directories.
**********************************************************************
File "techniques/ReflectometryILL.rst", line 913, in FIGARODetectorAngleGravityCorrection
Failed example:
    # reduction based on data from cycle 212, exp_EASY-952
    name = 'Cell_d2O'
    runs = '743465,743466'
    direct_run = '732252+732254,732255'
    ReflectometryILLAutoProcess(
          Run=runs,
          DirectRun=direct_run,
          OutputWorkspace=name,
          AngleOption='DetectorAngle',
          SummationType='Incoherent',
          WavelengthLowerBound=[3.5, 2.5],
          WavelengthUpperBound=[20, 19],
          DeltaQFractionBinning=0.5,
          GlobalScaleFactor=0.0484221,
          Cleanup='Cleanup ON',
          ReflFitStartWorkspaceIndex=25,
          ReflFitEndWorkspaceIndex=230,
          DirectFitStartWorkspaceIndex=25,
          DirectFitEndWorkspaceIndex=230,
          DirectLowAngleFrgHalfWidth=[3, 7],
          DirectHighAngleFrgHalfWidth=[3, 7],
          ReflLowAngleFrgHalfWidth=[3, 7],
          ReflHighAngleFrgHalfWidth=[3, 7],
          DirectLowAngleBkgOffset=5,
          DirectLowAngleBkgWidth=5,
          DirectHighAngleBkgOffset=5,
          DirectHighAngleBkgWidth=5,
          ReflLowAngleBkgOffset=5,
          ReflLowAngleBkgWidth=5,
          ReflHighAngleBkgOffset=5,
          ReflHighAngleBkgWidth=5,
          ReflFlatBackground='Background Average',
          DirectFlatBackground='Background Average',
          CorrectGravity=True
    )
    print("Number of output workspaces: {}".format(mtd[name].getNumberOfEntries()))
    print("Momentum exchange ranges: {:.4f}, {:.4f}".format(mtd[name][2].readX(0)[0], mtd[name][2].readX(0)[-1]))
    print('X unit: ' + mtd[name][2].getAxis(0).getUnit().unitID())
Exception raised:
    Traceback (most recent call last):
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 936, in do_set_property
        alg_object.setProperty(key, new_value)
    ValueError: Invalid value for property Run (list of str lists) from string "743465,743466": Unable to find file matching the string "743465", please check the data search directories.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/Users/danielmurphy/mambaforge/envs/mantid-developer/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest FIGARODetectorAngleGravityCorrection[0]>", line 5, in <module>
        ReflectometryILLAutoProcess(
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1068, in __call__
        set_properties(algm, *args, **final_keywords)
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 956, in set_properties
        do_set_property(key, value)
      File "/Users/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 939, in do_set_property
        raise e.__class__(msg) from e
    ValueError: Problem setting "Run" in ReflectometryILLAutoProcess-v1: Invalid value for property Run (list of str lists) from string "743465,743466": Unable to find file matching the string "743465", please check the data search directories.
3 items passed all tests:
   1 tests in AnalyzerlessEx
   1 tests in D17DetectorAngleCoherent
   1 tests in LoadingD17DirectBeam
**********************************************************************
2 items had failures:
   1 of   1 in D17UserAngleQuartz
   1 of   1 in FIGARODetectorAngleGravityCorrection
5 tests in 5 items.
3 passed and 2 failed.
***Test Failed*** 2 failures.
```

**Comment by AndreiSavici** [comment]
Works on Ubuntu 22.04. One test failed because I have newer Python `VesuvioTOFFit-v1` complains that `RuntimeError: module 'collections' has no attribute 'Iterable'`

**Review by KedoKudo — APPROVED** [review]
All doc test passed on Ubuntu_v22.04
