### PR TITLE
Fix autoscale color axis for nonortho view of MD(Event)Workspaces in sliceviewer

### LINKED ISSUE #33389: Unexpected exception in non-orthog view of sliceviewer when color axis autoscaled
**Describe the bug**
Regression introduced in #33336 - enabling non-orthog view in sliceviewer produces an exception realting to the updating 
```
Traceback (most recent call last):
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\view.py", line 425, in on_non_orthogonal_axes_toggle
    self.presenter.nonorthogonal_axes(state)
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 365, in nonorthogonal_axes
    self.show_all_data_requested()
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 239, in show_all_data_requested
    self.set_axes_limits(*limits)
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 256, in set_axes_limits
    self.data_limits_changed()
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 226, in data_limits_changed
    self.new_plot()  # automatically uses current display limits
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 121, in new_plot_MDE
    data_view.plot_MDH(
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\view.py", line 296, in plot_MDH_nonorthogonal
    self.draw_plot()
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\view.py", line 352, in draw_plot
    self.colorbar.update_clim()
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\colorbar\colorbar.py", line 264, in update_clim
    self._autoscale_clim()
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\colorbar\colorbar.py", line 298, in _autoscale_clim
    data = self.colorbar.mappable.get_array_clipped_to_bounds()
AttributeError: 'QuadMesh' object has no attribute 'get_array_clipped_to_bounds'
```

**To Reproduce**
(1) Create a workspace
```
md_3D = CreateMDWorkspace(Dimensions=3, Extents=[-0.5,0.5,-1,1,-2,2], 
    Names="H,K,L", Frames='HKL,HKL,HKL',Units='r.l.u.,r.l.u.,r.l.u.')
expt_info = CreateSampleWorkspace()
md_3D.addExperimentInfo(expt_info)
SetUB(Workspace=md_3D, c=2, gamma=120)
```
(2) Open `md_3D` in sliceviewer
(3) Click non-orthog view

**Expected behavior**
No exception - color axis auto scale would work

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
This fixes color axis autoscaling for MDEvent workspaces in nonortho mode - but for MDHisto the data array is not clipped to the axes limits (as it is not rebinned to axes limits).

The reason the nonorthogonal view behaves differently is that it is plotted using `pcolormesh` which returns a `QuadMesh` which doesn't have the `get_array_clipped_to_bounds` method that was introduced in #33336 for `ModestImage` (and `SamplingImage` for Workspace2D) which is produced with an adapted version of` imshow`.

To fix the issue for MDHisto we could add a pcolormesh function in `MantidAxes` that returns a `MantidQuadMesh`-like class with an additional `get_array_clipped_to_bounds` method?
Or make nonortho plots with `imshow` producing a `ModestImage` - it does seem to support transforms in the code.

**To test:**

(1) Create MDEventWorkspace
```
md_3D = CreateMDWorkspace(Dimensions=3, Extents=[-0.5,0.5,-1,1,-2,2], 
    Names="H,K,L", Frames='HKL,HKL,HKL',Units='r.l.u.,r.l.u.,r.l.u.')
expt_info = CreateSampleWorkspace()
md_3D.addExperimentInfo(expt_info)
SetUB(Workspace=md_3D, c=2, gamma=120)
FakeMDEventData(md_3D, EllipsoidParams='1e+04,0,0,0,1,0,0,0,1,0,0,0,1,0.02,0.06,1,1', RandomSeed='3873875')
```
(2) Open sliceviewer
(3) Turn on non-ortho view - should be no error
(4) Zoom and pan - autoscale should work
(5) Close sliceviewer and delete the `md_3D `workspace
(6) open `md_3D_svrebinned`  - an MDHistoWorkspace - in sliceviewer
(7) Zoom - no error but clim won't update

Fixes #33389

*This does not require release notes* because **it is covered by the release note of #33336 **

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Have made issues for next release to fix the bug autoscaling for MDHisto workspaces and a maintenance issue to add unit tests for colorbar.py. 
This doesn't require release notes as it is covered by the release note of #33336 - so I am marking it ready for review.

**Comment by sf1919** [comment]
In step 7 does clim mean colorbar limits?

**Comment by RichardWaiteSTFC** [comment]
> In step 7 does clim mean colorbar limits?

Yes, the limits on the cololrbar shouldn't update when zooming in on step 7 (or panning) on an MDHisto workspace (unless the original MDEvent workspace exists in the ADS)

**Review by sf1919 — APPROVED** [review]
I have undertaken a function test of the code and it all works as expected. Reviewing the code the change looks like a sensible one for the situation.
I therefore approve.
