### PR TITLE
Update logging calls so they work in sphinx v2.3

### LINKED ISSUE #27792: Documentation does not build with Sphinx >= 2.0.0
The api of various classes in Sphinx has changed in v2. The documentation build now falls over while reading the source pages as various classes do not have the expected attributes any longer.

Head of build log:
```
Running Sphinx v2.3.1
loading intersphinx inventory from https://h5py.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://pystog.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://developer.mantidproject.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1769 source files that are out of date
updating environment: [new config] 1769 added, 0 changed, 0 removed
reading sources... [  0%] algorithms/Abins-v1
runsphinx_html.py:97: RemovedInSphinx30Warning: sphinx.cmdline module is deprecated. Use sphinx.cmd.build instead.
  sys.exit(sphinx.cmdline.main(argv))
/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/util/docutils.py:285: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
Traceback (most recent call last):
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/io.py", line 350, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/io.py", line 137, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/mgigg/.virtualenvs/sphinx-v2/lib/python3.6/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 172, in run
    input_source=document['source'])
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2327, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2339, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2082, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2131, in run_directive
    result = directive_instance.run()
  File "/home/mgigg/Code/mantidproject/mantid/docs/sphinxext/mantiddoc/directives/base.py", line 140, in run
    skip_msg = self.skip()
  File "/home/mgigg/Code/mantidproject/mantid/docs/sphinxext/mantiddoc/directives/base.py", line 178, in skip
    env.app.verbose(msg)
AttributeError: 'Sphinx' object has no attribute 'verbose'

Exception occurred:
  File "/home/mgigg/Code/mantidproject/mantid/docs/sphinxext/mantiddoc/doctest.py", line 536, in doctest_to_xunit
    app.debug("Skipping xunit parsing for builder '%s'" % app.builder.name)
AttributeError: 'Sphinx' object has no attribute 'debug'
The full traceback has been saved in /tmp/sphinx-err-91oxitlh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Investigate and fix the issues.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The docs didn't build with Sphinx v2.3 due to some changes to the way logging is done in Sphinx between the current version (1.6) and version 2.3 This affected a small number of logging calls in the Mantid docs code.

Changes have been made so that Mantid docs build in both versions 1.6 and 2.3. The Sphinx version used by Mantid hasn't been moved on yet

**To test:**

Since the Sphinx version hasn't been moved on yet in the Mantid builds, testing this requires you to locally\temporarily move your sphinx version on to 2.3. You can check your currently installed version by running:

sphinx-build --version

The sphinx install that is used in the Mantid docs build can be moved forward to 2.x by running

easy_install -U Sphinx==2.3
(for some reason I had to run "easy_install-3 -U Sphinx==2.3" on Windows to avoid an error about a missing positional argument - but possible that's just me)

Build the docs (targets docs-html and docs-qthelp) and check the builds succeed

Fixes #27792

*This does not require release notes* because it's an internal technical change that doesn't have any external functional change

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — APPROVED** [review]
This looks good to me. I can now build the docs with Sphinx 2.4 :+1:
