### ISSUE TITLE
Plots not loading in project recovery

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#38650]
Found during manual testing for 6.12

**Describe the bug**

When project recovery tries to open plots it fails with the error:
```
A plot was unable to be loaded from the save file. Error: Line2D.set() got an unexpected keyword argument 'argType'
```

**To Reproduce**
Use the longer script from the first test [here](http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html), then plot a spectrum. Once project recovery has saved, crash Workbench with `SegFault`, restart Workbench, then click `Yes' in the project recovery window that appears.

**Expected behavior**

Plots should reappear

**Platform/Version (please complete the following information):**
 - OS: All
 - OS Version: N/A
 - Mantid Version 6.12

**Additional context**
Possibly caused by #38486

**Comment by walshmm** [comment]
This relates to #38486

**Comment by walshmm** [comment]
it is probably that [this line](https://github.com/mantidproject/mantid/blob/main/qt/python/mantidqt/mantidqt/project/plotsloader.py#L111) does not account for the new creation arg
