### ISSUE TITLE
‘nan’ is not a member of ‘std’

### ISSUE THREAD

**Issue by nvaytet** [mantidproject/mantid#22681]
### Expected behavior
Mantid should build on Ubuntu 18.04 with gcc7

### Actual behavior
It fails with error:
```
/home/nvaytet/work/mantid/temp/mantid/Framework/Algorithms/inc/MantidAlgorithms/ReflectometrySumInQ.h:61:25: error: ‘nan’ is not a member of ‘std’
     double horizon{std::nan("")};
```
### Steps to reproduce the behavior
Build mantid with gcc7

### Platforms affected
Ubuntu 18.04
