### PR TITLE
Add missing include target to DataHandling test

### PR DESCRIPTION
**Pull request by rosswhitfield**
The SaveNXcanSAS test currently fails to compile on Ubuntu 16.04 because it can't find `H5Cpp.h`. This fixes that.

```
FAILED: /usr/bin/c++   -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DENABLE_OPENCASCADE -DHAVE_STDINT_H -DMAKE_VATES -isystem /usr/include/nexus -isystem /usr/include/jsoncpp -I../Framework/Kernel/inc -I../Framework/Geometry/inc -I../Framework/API/inc -I../Framework/DataObjects/inc -isystem ../Testing/Tools/cxxtest -isystem ../Testing/Tools/gmock-1.7.0/include -isystem ../Testing/Tools/gmock-1.7.0/gtest/include -I../Framework/DataHandling/test/../../TestHelpers/inc -I../Framework/DataHandling/inc -I../Framework/DataHandling/../Nexus/inc -fopenmp -Wsuggest-override -Wall -Wextra -Wconversion -Winit-self -Wpointer-arith -Wcast-qual -Wcast-align -fno-common -Wno-deprecated -Wno-write-strings -Wno-unused-result -pedantic -Woverloaded-virtual -fno-operator-names -O3 -DNDEBUG   -std=gnu++14 -MMD -MT Framework/DataHandling/test/CMakeFiles/DataHandlingTest.dir/SaveNXcanSASTest.cpp.o -MF Framework/DataHandling/test/CMakeFiles/DataHandlingTest.dir/SaveNXcanSASTest.cpp.o.d -o Framework/DataHandling/test/CMakeFiles/DataHandlingTest.dir/SaveNXcanSASTest.cpp.o -c Framework/DataHandling/test/SaveNXcanSASTest.cpp
In file included from Framework/DataHandling/test/SaveNXcanSASTest.cpp:17:0:
/home/builder/jenkins-linode/workspace/master_clean-ubuntu-16.04/Framework/DataHandling/test/SaveNXcanSASTest.h:19:19: fatal error: H5Cpp.h: No such file or directory
```

_Does not need to be in the release notes._

**To test:**
- See if it now compiles on Ubuntu 16.04

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
LGTM :shipit:
