### PR TITLE
Fix Python extensions when compiled with clang on Linux 

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Open python extensions on Linux with `RTLD_GLOBAL` so that they share symbols across the process.

**Report to:** nobody

**To test:**

Compile mantid with clang on Linux. Fire up `bin/mantidpython` and `import mantid` - there should be no errors raised. Try out some algorithms.

*There is no associated issue*

*This does not require release notes* because **it is an internal change that users will not see.**

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rosswhitfield — APPROVED** [review]
:grinning: It works :tada:

**Comment by rosswhitfield** [comment]
`Framework` compiles but `MantidPlot` still fails with
```
/usr/bin/ld: MantidPlot/CMakeFiles/MantidPlot.dir/src/ProjectRecovery.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```

Adding `target_link_libraries ( MantidPlot LINK_PRIVATE -lpthread )` to `MantidPlot/CMakeLists.txt` fixes that.

Once that is fixed there is only one failing unittest `ITableWorkspaceTest`

```
540: ERROR [0.001s]: test_pickle_table_workspace (ITableWorkspaceTest.ITableWorkspaceTest)
540: ----------------------------------------------------------------------
540: Traceback (most recent call last):
540:   File "/home/rwp/mantid/Framework/PythonInterface/test/python/mantid/api/ITableWorkspaceTest.py", line 239, in test_pickle_table_workspace
540:     table2 = pickle.loads(p)
540:   File "/usr/lib/python2.7/pickle.py", line 1388, in loads
540:     return Unpickler(file).load()
540:   File "/usr/lib/python2.7/pickle.py", line 864, in load
540:     dispatch[key](self)
540:   File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
540:     value = func(*args)
540: RuntimeError: Add Data Object with empty name
```

But these can be fixed in a different PR unless you feel like fixing it all here.

**Comment by martyngigg** [comment]
Strange - I compiled MantidPlot on my Ubuntu 18.04 laptop and with `clang` & `clang++` and it all compiled - what version of clang are you using?

**Comment by martyngigg** [comment]
It also doesn't seem to compile on Ubuntu 16.04 with clang 3.8 due to a problem with `tbb`. Should we use `libstdc+++` or `libc++` do you think?

**Comment by rosswhitfield** [comment]
It failed for me on Ubuntu 18.04 with clang 6.0. I will set up a Jenkins build to run this and see what happens.
