### PR TITLE
Refs #22681 : This fixes the gcc7 compilation error

### LINKED ISSUE #22681: ‘nan’ is not a member of ‘std’
### Expected behavior
Mantid should build on Ubuntu 18.04 with gcc7

### Actual behavior
It fails with error:
```
/home/nvaytet/work/mantid/temp/mantid/Framework/Algorithms/inc/MantidAlgorithms/ReflectometrySumInQ.h:61:25: error: ‘nan’ is not a member of ‘std’
     double horizon{std::nan("")};
```
### Steps to reproduce the behavior
Build mantid with gcc7

### Platforms affected
Ubuntu 18.04

### PR DESCRIPTION
**Pull request by nvaytet**
Build was failing with ‘nan’ is not a member of ‘std’ on Ubuntu 18.04.

**Description of work.**

Added `#include <cmath>` in file `ReflectometrySumInQ.h`

**To test:**

Build Mantid with gcc7.

Fixes #22681 

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — APPROVED** [review]
Looks good to me :+1:
