### PR TITLE
Resolve compilation issue for gcc 8.2.1

### LINKED ISSUE #25222: jsoncpp ambiguous overload issue for long long
### Expected behavior

Mantid compiles

### Actual behavior

Compilation errors:
```
mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:114:16: error: call of overloaded 'Value(long long int)' is ambiguous
   return Json::Value(static_cast<JsonValueType>(value));

[...]

mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:114:16: error: call of overloaded 'Value(long long unsigned int)' is ambiguous
   return Json::Value(static_cast<JsonValueType>(value));
```

### Steps to reproduce the behavior

build with gcc 8.2.1 and jsoncpp 1.8.4

### Platforms affected

arch linux

### PR DESCRIPTION
**Pull request by mganeva**
**Description of work.**

Minor changes to resolve an issue with jsoncpp and ambiguous overloads when called
with long long/unsigned long long.

**To test:**

Check that nothing got broken

Fixes #25222.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
This did fix compiling with `gcc 8.2.1` but it's failing again, I'm guessing because of the recent changes in #25211

```
In file included from /home/ross/mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc:14,
                 from /home/ross/mantid/Framework/Kernel/src/ArrayProperty.cpp:10:
/home/ross/mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:44:20: error: redefinition of ‘struct Mantid::Kernel::pwvjdetail::ToCpp<long int>’
 template <> struct ToCpp<Json::Int64> {
                    ^~~~~~~~~~~~~~~~~~
/home/ross/mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:40:20: note: previous definition of ‘struct Mantid::Kernel::pwvjdetail::ToCpp<long int>’
 template <> struct ToCpp<long> {
                    ^~~~~~~~~~~
```

**Comment by mganeva** [comment]
It seems that this code fails to compile even without my changes
```c++
/// Specialization of ToCpp for long
template <> struct ToCpp<long> {
  long operator()(const Json::Value &value) { return value.asInt(); }
};
/// Specialization of ToCpp for int
template <> struct ToCpp<Json::Int64> {
  Json::Int64 operator()(const Json::Value &value) { return value.asInt64(); }
};
```
`gcc 8.2.1` takes `template <> struct ToCpp<Json::Int64>` as redefinition of `template <> struct ToCpp<long>`

Thanks for letting me know

**Review by rosswhitfield — APPROVED** [review]
