### ISSUE TITLE
jsoncpp ambiguous overload issue for long long

### ISSUE THREAD

**Issue by mganeva** [mantidproject/mantid#25222]
### Expected behavior

Mantid compiles

### Actual behavior

Compilation errors:
```
mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:114:16: error: call of overloaded 'Value(long long int)' is ambiguous
   return Json::Value(static_cast<JsonValueType>(value));

[...]

mantid/Framework/Kernel/inc/MantidKernel/PropertyWithValueJSON.h:114:16: error: call of overloaded 'Value(long long unsigned int)' is ambiguous
   return Json::Value(static_cast<JsonValueType>(value));
```

### Steps to reproduce the behavior

build with gcc 8.2.1 and jsoncpp 1.8.4

### Platforms affected

arch linux
