### PR TITLE
Reimplement #38486 to avoid project recovery error

### LINKED ISSUE #38650: Plots not loading in project recovery
Found during manual testing for 6.12

**Describe the bug**

When project recovery tries to open plots it fails with the error:
```
A plot was unable to be loaded from the save file. Error: Line2D.set() got an unexpected keyword argument 'argType'
```

**To Reproduce**
Use the longer script from the first test [here](http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html), then plot a spectrum. Once project recovery has saved, crash Workbench with `SegFault`, restart Workbench, then click `Yes' in the project recovery window that appears.

**Expected behavior**

Plots should reappear

**Platform/Version (please complete the following information):**
 - OS: All
 - OS Version: N/A
 - Mantid Version 6.12

**Additional context**
Possibly caused by #38486

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

The pr #38486 introduced a problem with project recovery (#38650) by adding a creation arg to all plots. These creating args eventually find themselves passed to an mpl plotting function when being recovered. This causes an error.

The original problem is that when you have a plot that has workspace data (plotted with a workspace name argument) **and** non-workspace data, renaming the plotted workspace threw and exception because the code assumed all sets of plotting arguments would have a workspace name.

I think instead of keeping track of a new creation arg, the original bug (key error) can be avoided by using `get()` on the creation arg dictionary to check for workspace names safely.

Added a test for the original bug. Haven't added one for project recovery because I think it was working correctly (feeding back the mpl error and not crashing).

Fixes #38650 
Fixes #38486

### To test:

Test the script from the original issue #38486 causes no problems.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by walshmm — APPROVED** [review]
This fix should work, I had originally introduced argType so we weren't passing around arbitrary dictionaries.  It would have been nice to keep but probably overblown for the scale of the original issue(minor).

**Review by thomashampson — APPROVED** [review]
This adds a test to expose the original bug, and resolves the new bug by fixing the original bug in a much simpler way. Good work.
