### PR TITLE
Fixes for building against Python 3

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes the mantid Python module C++/Python code & MantidPlot C++ Python code to be compatible with both Python 2 & 3.

Note that the Python plugins have not been touched and require more fixes.

**To test:**
- Check that the code base still builds with Python 2 and both Python works through vanilla Python, IPython 2 and MantidPlot.
- Check that the code base now builds with Python 3. As noted above the plugins don't work yet so in order use the mantid module you'll need to do `echo "python.plugins.directories=" >> ~/.mantid/Mantid.user.properties`

No issue number

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
Initial testing: I tested that it builds with python `3.4` on Ubuntu 14.04 and python `3.5` on Ubuntu 16.04 and Arch :+1:

ManitdPlot starts and the python algorithms aren't visible as expected. The visible algorithms appear to work when run from the gui. But if I tried to executed them from with the python interface or just within python they fail. _e.g._ `ws = CreateSampleWorkspace()` I get
```
>>> ws = CreateSampleWorkspace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rwp/python3-build/release/bin/mantid/simpleapi.py", line 856, in algorithm_wrapper
    lhs = _kernel.funcreturns.lhs_info(frame=frame)
AttributeError: module 'mantid.kernel' has no attribute 'funcreturns'
```
Should this be working at this point?

**Comment by martyngigg** [comment]
That should work at this point. I'll take a look.

**Comment by martyngigg** [comment]
@rosswhitfield I think I've finally got this thing to a an acceptable state to be merged. I still haven't fixed up the Python plugins for Python 3 but the standard `simpleapi` should work for the C++ algorithms and MantidPlot should start and be able to run python code.

**Comment by rosswhitfield** [comment]
I still can't run `ws = CreateSampleWorkspace()`, but I do get a different error now:
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mantid.simpleapi import *
FrameworkManager-[Notice] Welcome to Mantid 3.7.20160617.914
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
>>> ws = CreateSampleWorkspace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rwp/mantid/release/bin/mantid/simpleapi.py", line 861, in algorithm_wrapper
    set_properties(algm, *args, **final_keywords)
  File "/home/rwp/mantid/release/bin/mantid/simpleapi.py", line 814, in set_properties
    alg_object.setProperty(key, value)
ValueError: When converting parameter "OutputWorkspace": Unable to extract boost::shared_ptr<Workspace> from Python object
```

Should the unit tests compile? I'm getting
```
Building CXX object Framework/PythonInterface/test/cpp/CMakeFiles/PythonInterfaceCppTest.dir/PropertyWithValueFactoryTest.cpp.o
FAILED: /usr/bin/c++   -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_PYTHON_NO_LIB -DENABLE_OPENCASCADE -DHAVE_STDINT_H -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -isystem /usr/include/nexus -isystem /usr/include/jsoncpp -I../Framework/Kernel/inc -I../Framework/Geometry/inc -I../Framework/API/inc -isystem /usr/include/python3.4m -isystem /usr/lib/python3/dist-packages/numpy/core/include -I../Framework/PythonInterface/inc -isystem ../Testing/Tools/cxxtest -isystem ../Testing/Tools/gmock-1.7.0/include -isystem ../Testing/Tools/gmock-1.7.0/gtest/include -fopenmp -Wall -Wextra -Wconversion -Winit-self -Wpointer-arith -Wcast-qual -Wcast-align -fno-common -Wno-deprecated -Wno-write-strings -Wno-unused-result -pedantic -Woverloaded-virtual -fno-operator-names -O3 -DNDEBUG   -std=gnu++1y -MMD -MT Framework/PythonInterface/test/cpp/CMakeFiles/PythonInterfaceCppTest.dir/PropertyWithValueFactoryTest.cpp.o -MF Framework/PythonInterface/test/cpp/CMakeFiles/PythonInterfaceCppTest.dir/PropertyWithValueFactoryTest.cpp.o.d -o Framework/PythonInterface/test/cpp/CMakeFiles/PythonInterfaceCppTest.dir/PropertyWithValueFactoryTest.cpp.o -c Framework/PythonInterface/test/cpp/PropertyWithValueFactoryTest.cpp
In file included from Framework/PythonInterface/test/cpp/PropertyWithValueFactoryTest.cpp:17:0:
/home/rwp/mantid/Framework/PythonInterface/test/cpp/PropertyWithValueFactoryTest.h: In member function ‘void PropertyWithValueFactoryTest::test_builtin_type_creates_int_type_property_without_error()’:
/home/rwp/mantid/Framework/PythonInterface/test/cpp/PropertyWithValueFactoryTest.h:52:54: error: ‘PyInt_FromLong’ was not declared in this scope
     CREATE_PROPERTY_TEST_BODY(long, PyInt_FromLong(10));
                                                      ^
/home/rwp/mantid/Framework/PythonInterface/test/cpp/PropertyWithValueFactoryTest.h:33:38: note: in definition of macro ‘CREATE_PROPERTY_TEST_BODY’
     object pyvalue = object(handle<>(PythonCall));                             \
                                      ^
ninja: build stopped: subcommand failed.
```

**Comment by martyngigg** [comment]
I did miss the unit tests for Python 3 actually. They should be easy to fix.

I'l have another look at the algorithm stuff too. That error is odd.

**Comment by rosswhitfield** [comment]
I made a Jenkins MultiJob [here](http://builds.mantidproject.org/job/python3/) that runs on Ubuntu 14.04, 16.04 and Arch, so testing both python `3.4` and `3.5`. It's currently pointed at this branch but we can point it at master and add it to the critical tab once this is merged to make sure we don't have any regression. It currently just builds `MantidPlot` and `AllTests`. It doesn't run the tests as most of the python ones fail, maybe we can make it run a subset of the tests, _i.e._ currently passing ones.

Note: some of the Ubuntu 14.04 build servers are missing the required python3 dependencies. _e.g._ `python3-pyqt4` and `python3-sip-dev` on [`isis-ndw1441`](http://builds.mantidproject.org/job/master_clean-ubuntu-python3/1/console). But this is easy to fix.

There are a couple of other things I wanted to test before I give it the 👍 Monday...

**Comment by martyngigg** [comment]
Sounds good! I'll update the isis buildservers on Monday.

I'll also email the dev list to let everyone know and push to start writing 2/3 compatible code as standard.

**Comment by martyngigg** [comment]
I've updated the ISIS builders with the required python3 packages. I've also built a Python 3 variant  of the `python-sphinx-bootstrap-theme` in the mantid ppa: https://launchpad.net/~mantid/+archive/ubuntu/mantid

**Comment by rosswhitfield** [comment]
LGTM :shipit:
